### PR TITLE
Limit the number of pending send bytes in client

### PR DESCRIPTION
**Pull request by pramodin**
A limit can now be placed on the amount of pending data to be transmitted that is buffered in bytes. If there is no room the send call will return false to denote the caller needs to try sending it again later. The limit can be specified at a global level and also overridden on a per-client basis.

### CODE REVIEW

**Comment by PramodSSImmaneni** [comment]
Not sure why semver is failing even though there are only additions. Chetan is there any hard restriction on the classes that new methods cannot be added.

**Comment by 243826** [comment]
Addition does not fail semver. I'll take a look.

**Comment by PramodSSImmaneni** [comment]
Any updates guys @243826 or @vrozov

**Comment by 243826** [comment]
Pramod, can you check why it says that the server is broken? Also
separately can you look at how you can avoid volatile for keeping track of
bytes?

**Comment by PramodSSImmaneni** [comment]
Sounds good

**Comment by PramodSSImmaneni** [comment]
Chetan the build was failing because of this flag in pom.xml <breakBuildOnModifications>true</breakBuildOnModifications>

Made changes to avoid using volatile for normal counters and update counter visibility once in a while using a configurable timeout. Check it out.

**Pull request closed without merging**
